onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_aley_lc3/CLKtb
add wave -noupdate /tb_aley_lc3/RSTntb
add wave -noupdate /tb_aley_lc3/datap/CLK
add wave -noupdate /tb_aley_lc3/datap/RSTn
add wave -noupdate /tb_aley_lc3/datap/PC_EN
add wave -noupdate -divider {PC MUX}
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/b
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/c
add wave -noupdate -divider PC
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_Bus
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_Inc
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/PC
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/PC_Plus
add wave -noupdate -divider {GATE PC}
add wave -noupdate /tb_aley_lc3/datap/Inst22_GATE_PC/OP_A
add wave -noupdate -divider MAR
add wave -noupdate /tb_aley_lc3/datap/Inst1_MAR/BUS_IN
add wave -noupdate -divider MEMORY
add wave -noupdate /tb_aley_lc3/datap/Inst4_GATE_MDR/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst4_GATE_MDR/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MDR_IN
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MEM_IN
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/MEM_OUT
add wave -noupdate -divider {GATE MDR}
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MDR_IN
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MEM_IN
add wave -noupdate -divider IR
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/OP_Q
add wave -noupdate -divider ADD2MUX
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/a
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/b
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/c
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/d
add wave -noupdate -divider EXTENDERS
add wave -noupdate /tb_aley_lc3/datap/Inst10_5SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst6_6SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst7_9SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst8_11SEXT/OP_A
add wave -noupdate -divider ADD1MUX
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/a
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/b
add wave -noupdate -divider ADDER
add wave -noupdate /tb_aley_lc3/datap/Inst13_ADDER/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst13_ADDER/OP_B
add wave -noupdate -divider {MAR MUX}
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/b
add wave -noupdate -divider {GATE MAR MUX}
add wave -noupdate /tb_aley_lc3/datap/Inst17_GATE_MARMUX/OP_A
add wave -noupdate -divider REGFILE
add wave -noupdate /tb_aley_lc3/datap/Inst22_GATE_PC/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/DR
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/SR1
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/SR2
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/sEN
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/sFF
add wave -noupdate -divider SR2MUX
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/b
add wave -noupdate -divider ALU
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_B
add wave -noupdate -divider {GATE ALU}
add wave -noupdate /tb_aley_lc3/datap/Inst18_GATE_ALU/OP_A
add wave -noupdate -divider NZP
add wave -noupdate /tb_aley_lc3/datap/Inst19_NZP/OP_A
add wave -noupdate -divider FSM
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/CLK
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/MEM_EN
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/cpu_state
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/next_state
add wave -noupdate -divider {INPUT BLOCK}
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/b
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/c
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_Bus
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_Inc
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/PC
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/PC_Plus
add wave -noupdate /tb_aley_lc3/datap/Inst22_GATE_PC/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst1_MAR/BUS_IN
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/mem_wr_rd_add
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/Data_in
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MDR_IN
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MEM_IN
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MDR_IN
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MEM_IN
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/a
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/b
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/c
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/d
add wave -noupdate /tb_aley_lc3/datap/Inst10_5SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst6_6SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst7_9SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst8_11SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/a
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/b
add wave -noupdate /tb_aley_lc3/datap/Inst13_ADDER/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst13_ADDER/OP_B
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/b
add wave -noupdate /tb_aley_lc3/datap/Inst17_GATE_MARMUX/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst22_GATE_PC/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/DR
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/SR1
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/SR2
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/sEN
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/sFF
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/b
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_B
add wave -noupdate /tb_aley_lc3/datap/Inst18_GATE_ALU/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst19_NZP/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/CLK
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/MEM_EN
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/cpu_state
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/next_state
add wave -noupdate -divider {INPUT SIGNALS}
add wave -noupdate /tb_aley_lc3/CLKtb
add wave -noupdate /tb_aley_lc3/RSTntb
add wave -noupdate /tb_aley_lc3/datap/CLK
add wave -noupdate /tb_aley_lc3/datap/RSTn
add wave -noupdate /tb_aley_lc3/datap/S_MAR_OUT
add wave -noupdate /tb_aley_lc3/datap/S_MEM_OUT
add wave -noupdate /tb_aley_lc3/datap/S_MDR_BUS
add wave -noupdate /tb_aley_lc3/datap/S_IR_OUT
add wave -noupdate /tb_aley_lc3/datap/S_6SEXT_OUT
add wave -noupdate /tb_aley_lc3/datap/S_9SEXT_OUT
add wave -noupdate /tb_aley_lc3/datap/S_11SEXT_OUT
add wave -noupdate /tb_aley_lc3/datap/S_8ZEXT_OUT
add wave -noupdate /tb_aley_lc3/datap/S_5SEXT_OUT
add wave -noupdate /tb_aley_lc3/datap/S_A1M_OUT
add wave -noupdate /tb_aley_lc3/datap/S_A2M_OUT
add wave -noupdate /tb_aley_lc3/datap/S_ADDER_OUT
add wave -noupdate /tb_aley_lc3/datap/S_MARMUX_OUT
add wave -noupdate /tb_aley_lc3/datap/S_SR2MUX_OUT
add wave -noupdate /tb_aley_lc3/datap/S_SR1_OUT
add wave -noupdate /tb_aley_lc3/datap/S_SR2_OUT
add wave -noupdate /tb_aley_lc3/datap/S_PC_OUT
add wave -noupdate /tb_aley_lc3/datap/S_PCP_OUT
add wave -noupdate /tb_aley_lc3/datap/S_ALU_OUT
add wave -noupdate /tb_aley_lc3/datap/S_NZP_OUT
add wave -noupdate /tb_aley_lc3/datap/S_PCMUX_OUT
add wave -noupdate /tb_aley_lc3/datap/S_BUSSS
add wave -noupdate /tb_aley_lc3/datap/mem_en
add wave -noupdate /tb_aley_lc3/datap/read_write_en
add wave -noupdate /tb_aley_lc3/datap/MAR_EN
add wave -noupdate /tb_aley_lc3/datap/MDR_EN
add wave -noupdate /tb_aley_lc3/datap/Gate_MDR
add wave -noupdate /tb_aley_lc3/datap/Gate_MARMUX
add wave -noupdate /tb_aley_lc3/datap/Gate_ALU
add wave -noupdate /tb_aley_lc3/datap/Gate_PC
add wave -noupdate /tb_aley_lc3/datap/IR_EN
add wave -noupdate /tb_aley_lc3/datap/A1M_EN
add wave -noupdate /tb_aley_lc3/datap/SR2MUX_EN
add wave -noupdate /tb_aley_lc3/datap/MARMUX_EN
add wave -noupdate /tb_aley_lc3/datap/NZP_EN
add wave -noupdate /tb_aley_lc3/datap/PC_EN
add wave -noupdate /tb_aley_lc3/datap/REG_EN
add wave -noupdate /tb_aley_lc3/datap/DR_EN
add wave -noupdate /tb_aley_lc3/datap/SR1_EN
add wave -noupdate /tb_aley_lc3/datap/SR2_EN
add wave -noupdate /tb_aley_lc3/datap/A2M_EN
add wave -noupdate /tb_aley_lc3/datap/ALU_EN
add wave -noupdate /tb_aley_lc3/datap/PCMUX_EN
add wave -noupdate /tb_aley_lc3/datap/BUSSS
add wave -noupdate /tb_aley_lc3/datap/Inst1_MAR/CLK
add wave -noupdate /tb_aley_lc3/datap/Inst1_MAR/MAR_EN
add wave -noupdate /tb_aley_lc3/datap/Inst1_MAR/RST
add wave -noupdate /tb_aley_lc3/datap/Inst1_MAR/BUS_IN
add wave -noupdate /tb_aley_lc3/datap/Inst1_MAR/MAR_OUT
add wave -noupdate /tb_aley_lc3/datap/Inst1_MAR/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/CLK
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/mem_wr_rd_add
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/Data_in
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/read_write_en
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/mem_en
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/MEM_OUT
add wave -noupdate /tb_aley_lc3/datap/Inst2_MEM/SMEM_OUT
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/CLK
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MDR_EN
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/RST
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MDR_IN
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MEM_IN
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/MDR_OUT
add wave -noupdate /tb_aley_lc3/datap/Inst3_MDR/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst4_GATE_MDR/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst4_GATE_MDR/EN
add wave -noupdate /tb_aley_lc3/datap/Inst4_GATE_MDR/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst4_GATE_MDR/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/clk
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/RST
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/EN
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst5_IR/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst6_6SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst6_6SEXT/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst6_6SEXT/N
add wave -noupdate /tb_aley_lc3/datap/Inst6_6SEXT/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst7_9SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst7_9SEXT/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst7_9SEXT/N
add wave -noupdate /tb_aley_lc3/datap/Inst7_9SEXT/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst8_11SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst8_11SEXT/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst8_11SEXT/N
add wave -noupdate /tb_aley_lc3/datap/Inst8_11SEXT/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst9_8ZEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst9_8ZEXT/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst9_8ZEXT/N
add wave -noupdate /tb_aley_lc3/datap/Inst9_8ZEXT/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst10_5SEXT/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst10_5SEXT/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst10_5SEXT/N
add wave -noupdate /tb_aley_lc3/datap/Inst10_5SEXT/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/a
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/b
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/c
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/d
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/s
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/y
add wave -noupdate /tb_aley_lc3/datap/Inst11_A2M/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/b
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/s
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/y
add wave -noupdate /tb_aley_lc3/datap/Inst12_MARMUX/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst13_ADDER/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst13_ADDER/OP_B
add wave -noupdate /tb_aley_lc3/datap/Inst13_ADDER/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst13_ADDER/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/a
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/b
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/s
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/y
add wave -noupdate /tb_aley_lc3/datap/Inst14_A1M/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/b
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/s
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/y
add wave -noupdate /tb_aley_lc3/datap/Inst15_SR2MUX/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_B
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/sel
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_As
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/OP_Bs
add wave -noupdate /tb_aley_lc3/datap/Inst16_ALU/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst17_GATE_MARMUX/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst17_GATE_MARMUX/EN
add wave -noupdate /tb_aley_lc3/datap/Inst17_GATE_MARMUX/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst17_GATE_MARMUX/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst18_GATE_ALU/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst18_GATE_ALU/EN
add wave -noupdate /tb_aley_lc3/datap/Inst18_GATE_ALU/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst18_GATE_ALU/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst19_NZP/clk
add wave -noupdate /tb_aley_lc3/datap/Inst19_NZP/RST
add wave -noupdate /tb_aley_lc3/datap/Inst19_NZP/EN
add wave -noupdate /tb_aley_lc3/datap/Inst19_NZP/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst19_NZP/OP_NZP
add wave -noupdate /tb_aley_lc3/datap/Inst19_NZP/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/a
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/b
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/c
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/s
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/y
add wave -noupdate /tb_aley_lc3/datap/Inst20_PCMUX/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/clk
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/RST
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/EN
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_Bus
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/OP_Inc
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/PC
add wave -noupdate /tb_aley_lc3/datap/Inst21_PC/PC_Plus
add wave -noupdate /tb_aley_lc3/datap/Inst22_GATE_PC/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst22_GATE_PC/EN
add wave -noupdate /tb_aley_lc3/datap/Inst22_GATE_PC/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst22_GATE_PC/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/CLK
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/DR
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/LD_REG
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/SR1
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/SR2
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/OP_Q1
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/OP_Q2
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/sEN
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/sFF
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(0)/regh0/clk
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(0)/regh0/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(0)/regh0/en
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(0)/regh0/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(0)/regh0/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(0)/regh0/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(1)/regh0/clk
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(1)/regh0/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(1)/regh0/en
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(1)/regh0/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(1)/regh0/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(1)/regh0/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(2)/regh0/clk
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(2)/regh0/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(2)/regh0/en
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(2)/regh0/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(2)/regh0/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(2)/regh0/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(3)/regh0/clk
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(3)/regh0/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(3)/regh0/en
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(3)/regh0/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(3)/regh0/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(3)/regh0/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(4)/regh0/clk
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(4)/regh0/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(4)/regh0/en
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(4)/regh0/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(4)/regh0/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(4)/regh0/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(5)/regh0/clk
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(5)/regh0/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(5)/regh0/en
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(5)/regh0/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(5)/regh0/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(5)/regh0/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(6)/regh0/clk
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(6)/regh0/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(6)/regh0/en
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(6)/regh0/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(6)/regh0/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(6)/regh0/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(7)/regh0/clk
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(7)/regh0/RST
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(7)/regh0/en
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(7)/regh0/OP_A
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(7)/regh0/OP_Q
add wave -noupdate /tb_aley_lc3/datap/Inst23_REGARRAY/g0(7)/regh0/S_D
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/CLK
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/MEM_EN
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/cpu_state
add wave -noupdate /tb_aley_lc3/datap/Inst24_FSM/next_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {390 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 302
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {224 ns} {515 ns}
